name: Deploy Paper List Web App

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run every week on Sunday at midnight UTC
  workflow_dispatch:  # Allow manual triggering

# Add permissions block here
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install beautifulsoup4
      
      - name: Generate initial paper list
        run: |
          python select_papers.py
      
      - name: Create static site directory
        run: |
          mkdir -p site
          cp -r static site/
          cp templates/index.html site/index.html
      
      - name: Modify index.html for static site
        run: |
          python deploy_script.py
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true 